### ISSUE TITLE
Error deploying on Heroku

### ISSUE THREAD

**Issue by gblachonupg** [opentok/opentok-rtc#650]
Hello,

I have this error when deploying master branch to Heroku : 

```
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  8.0.x
       engines.npm (package.json):   2.14.x
       
       Resolving node version 8.0.x...
       Downloading and installing node 8.0.0...
       Bootstrapping npm 2.14.x (replacing 5.0.0)...
       npm 2.14.x installed
       
-----> Installing dependencies
       Installing node modules (package.json + package-lock)
       
       > ejs@2.7.4 postinstall /tmp/build_b5ba7a2b/node_modules/ejs
       > node ./postinstall.js
       
       
       > geckodriver@1.20.0 postinstall /tmp/build_b5ba7a2b/node_modules/geckodriver
       > node index.js
       
       /tmp/build_b5ba7a2b/node_modules/geckodriver/node_modules/tar/node_modules/mkdirp/lib/opts-arg.js:7
           opts = { mode: 0o777, fs, ...opts }
                                     ^^^
       
       SyntaxError: Unexpected token ...
           at createScript (vm.js:74:10)
           at Object.runInThisContext (vm.js:116:10)
           at Module._compile (module.js:533:28)
           at Object.Module._extensions..js (module.js:580:10)
           at Module.load (module.js:503:32)
           at tryModuleLoad (module.js:466:12)
           at Function.Module._load (module.js:458:3)
           at Module.require (module.js:513:17)
           at require (internal/module.js:11:18)
           at Object.<anonymous> (/tmp/build_b5ba7a2b/node_modules/geckodriver/node_modules/tar/node_modules/mkdirp/index.js:1:79)
       
       > fibers@3.1.1 install /tmp/build_b5ba7a2b/node_modules/wdio/node_modules/fibers
       > node build.js || nodejs build.js
       
       `linux-x64-57-glibc` exists; testing
       Binary is fine; exiting
       
       > fibers@2.0.2 install /tmp/build_b5ba7a2b/node_modules/wdio-mocha-framework/node_modules/wdio-sync/node_modules/fibers
       > node build.js || nodejs build.js
       
       `linux-x64-57` exists; testing
       Binary is fine; exiting
       
       > sauce-connect-launcher@1.2.7 postinstall /tmp/build_b5ba7a2b/node_modules/wdio-sauce-service/node_modules/sauce-connect-launcher
       > node scripts/install.js || nodejs scripts/install.js
       
       
       > iltorb@2.4.5 install /tmp/build_b5ba7a2b/node_modules/grunt-contrib-compress/node_modules/iltorb
       > node ./scripts/install.js || node-gyp rebuild
       
       info looking for cached prebuild @ /tmp/npmcache.9zIvU/_prebuilds/488314-iltorb-v2.4.5-node-v57-linux-x64.tar.gz
       http request GET https://github.com/nstepien/iltorb/releases/download/v2.4.5/iltorb-v2.4.5-node-v57-linux-x64.tar.gz
       http 200 https://github.com/nstepien/iltorb/releases/download/v2.4.5/iltorb-v2.4.5-node-v57-linux-x64.tar.gz
       info downloading to @ /tmp/npmcache.9zIvU/_prebuilds/488314-iltorb-v2.4.5-node-v57-linux-x64.tar.gz.2896-81c8d8dee5563.tmp
       info renaming to @ /tmp/npmcache.9zIvU/_prebuilds/488314-iltorb-v2.4.5-node-v57-linux-x64.tar.gz
       info unpacking @ /tmp/npmcache.9zIvU/_prebuilds/488314-iltorb-v2.4.5-node-v57-linux-x64.tar.gz
       info unpack resolved to /tmp/build_b5ba7a2b/node_modules/grunt-contrib-compress/node_modules/iltorb/build/bindings/iltorb.node
       info unpack required /tmp/build_b5ba7a2b/node_modules/grunt-contrib-compress/node_modules/iltorb/build/bindings/iltorb.node successfully
       info install Successfully installed iltorb binary!
       
       > core-js@2.6.11 postinstall /tmp/build_b5ba7a2b/node_modules/karma/node_modules/core-js
       > node -e "try{require('./postinstall')}catch(e){}"
       
       
       > core-js@2.6.11 postinstall /tmp/build_b5ba7a2b/node_modules/wdio-mocha-framework/node_modules/babel-runtime/node_modules/core-js
       > node -e "try{require('./postinstall')}catch(e){}"
       
       
       > core-js@2.6.11 postinstall /tmp/build_b5ba7a2b/node_modules/wdio/node_modules/webdriverio/node_modules/babel-runtime/node_modules/core-js
       > node -e "try{require('./postinstall')}catch(e){}"
       
       npm ERR! Linux 4.4.0-1077-aws
       npm ERR! argv "/tmp/build_b5ba7a2b/.heroku/node/bin/node" "/tmp/build_b5ba7a2b/.heroku/node/bin/npm" "install" "--production=false" "--unsafe-perm" "--userconfig" "/tmp/build_b5ba7a2b/.npmrc"
       npm ERR! node v8.0.0
       npm ERR! npm  v2.14.22
       npm ERR! code ELIFECYCLE
       
       npm ERR! geckodriver@1.20.0 postinstall: `node index.js`
       npm ERR! Exit status 1
       npm ERR! 
       npm ERR! Failed at the geckodriver@1.20.0 postinstall script 'node index.js'.
       npm ERR! This is most likely a problem with the geckodriver package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     node index.js
       npm ERR! You can get information on how to open an issue for this project with:
       npm ERR!     npm bugs geckodriver
       npm ERR! Or if that isn't available, you can get their info via:
       npm ERR! 
       npm ERR!     npm owner ls geckodriver
       npm ERR! There is likely additional logging output above.
       
       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/build_b5ba7a2b/npm-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

**Comment by kbravh** [comment]
@gblachonupg It looks like the error is because your Heroku server is on Node 8.0.0, which doesn't support the spread operator that's being used `opts = { mode: 0o777, fs, ...opts }`. If you upgrade to Node 8.16.0 (the LTS version) or newer, this error should not occur.
